# Generated by Django 3.0.8 on 2020-08-04 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfshare', '0002_posta_postb_postc_postd_poste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postb',
            name='author',
        ),
        migrations.RemoveField(
            model_name='postc',
            name='author',
        ),
        migrations.RemoveField(
            model_name='postd',
            name='author',
        ),
        migrations.RemoveField(
            model_name='poste',
            name='author',
        ),
        migrations.DeleteModel(
            name='Posta',
        ),
        migrations.DeleteModel(
            name='Postb',
        ),
        migrations.DeleteModel(
            name='Postc',
        ),
        migrations.DeleteModel(
            name='Postd',
        ),
        migrations.DeleteModel(
            name='Poste',
        ),
    ]
