# Generated by Django 3.0.8 on 2020-08-04 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfshare', '0004_post2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post2',
        ),
    ]
