# Generated by Django 3.0.8 on 2020-08-04 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfshare', '0005_delete_post2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
